# © 2025 Matthew Vallance. All rights reserved.
# COMP1682 Final Year Project.
# Purpose: Script to test BLEU scoring
# Note: Download Conceptual Captions validation dataset from https://ai.google.com/research/ConceptualCaptions/download
import csv
from nltk.translate.bleu_score import corpus_bleu, sentence_bleu


def get_conceptual_captions():
    cc_lines = []
    with open("conceptual_captions/CC_Labels.tsv", "r") as f:
        read_file = csv.reader(f, delimiter="\t")
        count = 0
        for row in read_file:
            cc_lines.append(row)
            print("Row: ", count)
            count += 1
        print("Read rows: ", count)

    return cc_lines


class BLEUScoring:
    def __init__(self, candidates=None):
        self.conceptual_captions = get_conceptual_captions()
        # Get all reference image URLs
        self.reference_image_urls = [image[1] for image in self.conceptual_captions]
        # Get all reference captions
        self.reference_captions = [caption[0] for caption in self.conceptual_captions]
        # This will be captions generated by the model
        self.candidates = candidates

    def get_corpus_bleu_score(self):
        score = corpus_bleu(self.reference_captions, self.candidates)
        return score

    def get_sentence_bleu_score(self):
        score = sentence_bleu(self.reference_captions, self.candidates)
        return score


if __name__ == "__main__":
    bleu = BLEUScoring()
